name: Pipeline Deployment
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    outputs:
      lint-status: ${{ steps.lint.outputs.status }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install deps
      - run: npm install
      - name: Run lint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install deps
        run: npm install
      - name: Run tests
        # run: npm run test
        run: |
         npm run test
         echo "Tests completed"
  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install deps
        run: npm install
      - name: Run build
        run: |
         npm run build
         echo "Build completed"
  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test, build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install deps
        run: npm install
      - name: Run deploy
        run: |
         npm run deploy
         echo "Deploy completed"