name: Triggered for new issues
on: issues
# concurrency:
#   group: ${{ github.workflow }}-${{ github.event.issue.number }}
#   cancel-in-progress: true
jobs:
  event-details:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: log event details
        run: echo '${{ toJson(github.event.issue) }}'